stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_processing:
    cmd: python src/data_processing.py
    deps:
    - data/raw
    - src/data_processing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    outs:
    - model.pkl
