name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cml  # Ensure cml is installed

      - name: Run main file
        run: |
          python main.py

      - name: Run Tests
        run: |
          python -m unittest discover

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GIT_SECRET }}
        run: |
          echo "# First Line of our report" >> report.md
         
          cml comment create report.md
