name: ci-pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirement.txt
          pip install --upgrade pip setuptools
          pip install cloud-ml-sdk  # Install cloud-ml-sdk if it's not included in requirement.txt

      - name: Create reports
        env:
          REPO_TOKEN: ${{ secrets.GIT_SECRET }}
        run: |
          echo "# first line of reports" >> report.md
          cml comment create report.md  # Assuming cml is correctly set up and authenticated

      
