name: ci-pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip setuptools

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Create reports
        
        run: |
          echo "# first line of reports" >> report.md
          cml comment create report.md --token ${{ secrets.GIT.SECRET}}  # Reference the secret
